### ISSUE TITLE
Codice di segnalazione di un messaggio nella Preview Pianta US

### ISSUE THREAD

**Issue by gabcicc** [pyarchinit/pyarchinit_beta_test_dev#145]
Premendo il messaggio Preview Pianta US dope il messaggio corretto (Modalità Preview US attivata), si presenta il seguente messaggio:

Layer to Set
[<qgis.gui.QgsMapCanvasLayer object at 0x1264a2f28>, <qgis.gui.QgsMapCanvasLayer object at 0x1264ef0e8>]

**Comment by enzococca** [comment]
se provi a fare la visualizzazione di un layer alla volta ti funziona? 
grazie

EC

**Comment by gabcicc** [comment]
Nel senso faccio una ricerca mirata ad un unica US e poi provo a visualizzarla?
In questo si mi da lo stesso il messaggio.

Altrimenti non ho chiaro la domanda
Gabriele

**Comment by enzococca** [comment]
si in questo senso.... l'errore ce l'ho anche io ma solo se interrogo più livelli. se interrogo un livello alla volta mi funziona. In questo periodo stiamo aggiustando un pò di cose e quindi è probabile che si creano nuovi bug. Solo un ultima domanda: che versione di pyarchinit stasi usando: versione scaricata dal repo di qgis o da github?

Cmq grazie per la segnalazione, vedrò risolvere il problema il prima possibile.

EC
